services:
    event.authentication_success_listener:
            class: App\User\Infrastructure\EventListener\JWTAuthenticationSuccessListener
            arguments:
              - "@simple_bus.command_bus"
              - "@monolog.logger"
            tags:
                - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }